# Generated by Django 3.2.9 on 2021-11-19 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsimagemodel',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to='image/20211119183358/', verbose_name='pictures'),
        ),
        migrations.AlterField(
            model_name='productsimagemodel',
            name='prod',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='prod', to='products.productsmodel', verbose_name='prod'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='file/20211119183358/', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='prod_name',
            field=models.CharField(max_length=100, verbose_name='prod_name'),
        ),
    ]
