# Generated by Django 3.2.9 on 2021-11-19 19:02

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211119_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productsmodel',
            name='file',
        ),
        migrations.RemoveField(
            model_name='productsmodel',
            name='prod_name',
        ),
        migrations.AlterField(
            model_name='productsimagemodel',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to='image/20211119190224/'),
        ),
        migrations.AlterField(
            model_name='productsimagemodel',
            name='prod',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='prod', to='products.productsmodel'),
        ),
        migrations.CreateModel(
            name='ProductsModelTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('prod_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='file/20211119190224/')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.productsmodel')),
            ],
            options={
                'verbose_name': 'products model Translation',
                'db_table': 'products_productsmodel_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases = (parler.models.TranslatableModel, models.Model),
        ),
    ]
