# Generated by Django 3.2.9 on 2021-12-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20211202_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodeltranslation',
            name='picture',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='productsimagemodel',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to='image/20211203173616/'),
        ),
        migrations.AlterField(
            model_name='productsmodeltranslation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='file/20211203173616'),
        ),
    ]
